### ISSUE TITLE
sorry not related to this but this is the only place i cound find to send a message

### ISSUE THREAD

**Issue by SArpnt** [BSquareII/BSquare_BytebeatComposer#1]
about the archive repo you made, i'm not deleting the *bytebeat website*, i'm just taking it off github. microsoft has been training ai models off various repos without permission, they're going to force 2fa soon, etc. just various annoying and unethical things.

i already have the new website up at bytebeat.ficial.net, and it should be permanent since i own the domain and will be using it for many things. i'll have all the code in a public and documented place soon enough.

i don't think i really want the repo archived especially without a link to the new website because it implies that i've stopped working on it. i'd rather people just find the new website.

you also didn't *really* archive the repo either, it's missing most of the branches (which contain important things!) and has no issues or pull requests

**Comment by BSquareII** [comment]
oh alright, i guess i will have to delete that one then. also i did see the warning message on your bytebeat composer that you would soon put the source code there on the new website.
